// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "a2f64dc2-9c24-41a4-885e-212f01707954");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1575221355);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1575221475);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1575260530);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1575257165);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1575257045);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1575221235);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1575221715);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1575221595);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 921600);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1575220845);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 77);
user_pref("browser.newtabpage.activity-stream.impressionId", "{134f60d7-3951-45e1-929a-486eb4dd36a2}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1575187200);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1575260526034");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1575262337034");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1575260519661");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1575264119661");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20190215001400");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1575256899");
user_pref("browser.slowStartup.averageTime", 7372);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20190215001400");
user_pref("browser.startup.homepage_override.mstone", "65.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1575220853688");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "65.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "200df8c0a6ff44938c9f1e8aa882db42");
user_pref("extensions.blocklist.lastModified", "Fri, 29 Nov 2019 22:22:46 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1575221357);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20190215001400");
user_pref("extensions.lastAppVersion", "65.0.1");
user_pref("extensions.lastPlatformVersion", "65.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"9b14927a-e5e9-414f-b3eb-52e7e3e8ff33\",\"screenshots@mozilla.org\":\"4f2b96a5-ffde-476c-917a-f15a11aa9b3d\",\"webcompat-reporter@mozilla.org\":\"db874506-876c-46a5-90d9-546903d8a33e\",\"webcompat@mozilla.org\":\"ac457e32-b6eb-49af-a02d-6c0e5e84b887\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("idle.lastDailyNotification", 1575221183);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1575220979);
user_pref("media.gmp-gmpopenh264.version", "1.6");
user_pref("media.gmp-manager.buildID", "20190215001400");
user_pref("media.gmp-manager.lastCheck", 1575220974);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1575221183);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "c4580be3-0a45-400a-808c-d2117b21dc2e");
user_pref("security.sandbox.plugin.tempDirSuffix", "716f7139-8923-4685-8d92-fb83166f1609");
user_pref("services.blocklist.addons.checked", 1575220994);
user_pref("services.blocklist.gfx.checked", 1575220994);
user_pref("services.blocklist.onecrl.checked", 1575220994);
user_pref("services.blocklist.pinning.checked", 1575220994);
user_pref("services.blocklist.plugins.checked", 1575220994);
user_pref("services.settings.clock_skew_seconds", -227);
user_pref("services.settings.last_update_seconds", 1575221469);
user_pref("services.settings.main.language-dictionaries.last_check", 1575220994);
user_pref("services.settings.main.sites-classification.last_check", 1575220994);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1575221183);
user_pref("toolkit.startup.last_success", 1575256894);
user_pref("toolkit.telemetry.cachedClientID", "60a3bdb7-88ff-460c-932b-c48b01731fc5");
user_pref("toolkit.telemetry.previousBuildID", "20190215001400");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
